# Generated by Django 4.0.2 on 2022-02-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_post_user'),
        ('main_app', '0004_location_description'),
    ]

    operations = [
    ]
